### Get all contacts
GET http://localhost:3000/users
Content-Type: application/json

###

### Get a single contact by ID
GET http://localhost:3000/users/681e6a8dc40272c15035c0ad
Content-Type: application/json
